# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python{2_7,3_5} )

inherit distutils-r1

DESCRIPTION="Natural language pipeline"
HOMEPAGE="https://pypi.python.org/pypi/polyglot"
SRC_URI="http://polyglot.cs.stonybrook.edu/~polyglot/index.json
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/pam/pam.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/it/it.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/hsb/hsb.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sah/sah.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/hi/hi.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/fr/fr.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/es/es.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/vi/vi.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ar/ar.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/mk/mk.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ps/ps.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sh/sh.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/arz/arz.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/nn/nn.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/su/su.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/scn/scn.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/az/az.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/bg/bg.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/yo/yo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/tg/tg.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ka/ka.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/tt/tt.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/gl/gl.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/mg/mg.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ug/ug.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/am/am.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/vec/vec.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/yi/yi.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/no/no.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/als/als.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/et/et.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/vls/vls.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/dv/dv.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ja/ja.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ilo/ilo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ht/ht.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/be/be.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/el/el.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/os/os.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/cy/cy.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ml/ml.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sq/sq.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/mr/mr.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/hy/hy.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sl/sl.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ko/ko.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/br/br.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ga/ga.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/lb/lb.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/bn/bn.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sr/sr.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/hif/hif.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/jv/jv.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/fi/fi.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/gan/gan.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ky/ky.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ca/ca.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/qu/qu.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/hr/hr.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/nl/nl.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sv/sv.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/io/io.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/tl/tl.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sa/sa.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/pms/pms.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ast/ast.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/da/da.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ceb/ceb.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/fy/fy.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/kn/kn.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sco/sco.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/mt/mt.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sw/sw.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/li/li.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/war/war.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/lmo/lmo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/uz/uz.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ku/ku.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/lv/lv.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/my/my.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/an/an.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/vo/vo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/se/se.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/fo/fo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/kk/kk.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/te/te.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/uk/uk.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/as/as.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/cv/cv.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/szl/szl.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/tk/tk.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ro/ro.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/fa/fa.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/bo/bo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/la/la.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/sk/sk.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/si/si.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/bar/bar.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/is/is.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/mn/mn.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/wa/wa.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/pt/pt.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ur/ur.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/gu/gu.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/gv/gv.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ta/ta.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/km/km.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/en/en.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ms/ms.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ce/ce.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/bpy/bpy.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/af/af.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/eu/eu.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/pl/pl.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/de/de.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/eo/eo.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/id/id.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/oc/oc.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/zh/zh.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/cs/cs.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/he/he.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/rm/rm.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/lt/lt.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/tr/tr.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ne/ne.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/bs/bs.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ia/ia.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/diq/diq.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/or/or.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/hu/hu.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/gd/gd.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ba/ba.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/th/th.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/pa/pa.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sgns2/ru/ru.sgns.model.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/it/it.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/hi/hi.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/fr/fr.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/es/es.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/vi/vi.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ar/ar.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/mk/mk.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sh/sh.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/nn/nn.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/az/az.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/bg/bg.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ka/ka.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/gl/gl.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/yi/yi.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/no/no.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/et/et.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ja/ja.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ht/ht.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/be/be.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/el/el.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/cy/cy.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sq/sq.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/mr/mr.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/hy/hy.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sl/sl.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ko/ko.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ga/ga.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/bn/bn.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sr/sr.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/fi/fi.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ca/ca.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/hr/hr.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/nl/nl.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sv/sv.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/tl/tl.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/da/da.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/kn/kn.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/mt/mt.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sw/sw.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/lv/lv.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/te/te.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/uk/uk.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ro/ro.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/fa/fa.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/la/la.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/sk/sk.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/is/is.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/pt/pt.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ur/ur.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/gu/gu.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ta/ta.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/km/km.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/en/en.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ms/ms.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/af/af.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/eu/eu.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/pl/pl.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/de/de.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/eo/eo.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/id/id.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/zh/zh.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/cs/cs.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/lt/lt.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/tr/tr.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/bs/bs.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/hu/hu.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/th/th.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/unipos/ru/ru.model.npz
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/it/it_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/hi/hi_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/fr/fr_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/es/es_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/vi/vi_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ar/ar_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/bg/bg_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/no/no_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/et/et_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ja/ja_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/el/el_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/sl/sl_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ko/ko_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/sr/sr_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/fi/fi_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ca/ca_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/hr/hr_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/nl/nl_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/sv/sv_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/tl/tl_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/da/da_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/lv/lv_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/uk/uk_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ro/ro_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/fa/fa_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/sk/sk_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/pt/pt_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/en/en_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ms/ms_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/pl/pl_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/de/de_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/id/id_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/zh/zh_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/cs/cs_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/he/he_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/lt/lt_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/tr/tr_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/hu/hu_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/th/th_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/ner2/ru/ru_ner.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/pam/pam.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/it/it.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/hsb/hsb.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sah/sah.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/hi/hi.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/fr/fr.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/es/es.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/vi/vi.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ar/ar.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/mk/mk.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ps/ps.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sh/sh.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/arz/arz.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/nn/nn.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/su/su.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/scn/scn.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/az/az.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/bg/bg.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/yo/yo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/tg/tg.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ka/ka.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/tt/tt.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/gl/gl.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/mg/mg.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ug/ug.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/am/am.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/vec/vec.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/yi/yi.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/no/no.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/als/als.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/et/et.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/vls/vls.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/dv/dv.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ja/ja.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ilo/ilo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ht/ht.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/be/be.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/el/el.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/os/os.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/cy/cy.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ml/ml.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sq/sq.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/mr/mr.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/hy/hy.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sl/sl.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ko/ko.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/br/br.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ga/ga.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/lb/lb.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/bn/bn.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sr/sr.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/hif/hif.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/jv/jv.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/fi/fi.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/gan/gan.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ky/ky.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ca/ca.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/qu/qu.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/hr/hr.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/nl/nl.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sv/sv.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/io/io.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/tl/tl.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sa/sa.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/pms/pms.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ast/ast.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/da/da.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ceb/ceb.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/fy/fy.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/kn/kn.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sco/sco.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/mt/mt.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sw/sw.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/li/li.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/war/war.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/lmo/lmo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/uz/uz.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ku/ku.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/lv/lv.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/my/my.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/an/an.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/vo/vo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/se/se.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/fo/fo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/kk/kk.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/te/te.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/uk/uk.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/as/as.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/cv/cv.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/szl/szl.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/tk/tk.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ro/ro.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/fa/fa.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/bo/bo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/la/la.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/sk/sk.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/si/si.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/bar/bar.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/is/is.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/mn/mn.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/wa/wa.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/pt/pt.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ur/ur.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/gu/gu.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/gv/gv.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ta/ta.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/km/km.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/en/en.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ms/ms.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ce/ce.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/bpy/bpy.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/af/af.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/eu/eu.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/pl/pl.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/de/de.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/eo/eo.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/id/id.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/oc/oc.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/zh/zh.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/cs/cs.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/he/he.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/rm/rm.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/lt/lt.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/tr/tr.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ne/ne.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/bs/bs.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ia/ia.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/diq/diq.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/or/or.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/hu/hu.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/gd/gd.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ba/ba.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/th/th.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/pa/pa.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/counts2/ru/ru.voc.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/it/transliteration.it.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/hi/transliteration.hi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/fr/transliteration.fr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/es/transliteration.es.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/vi/transliteration.vi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ar/transliteration.ar.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/mk/transliteration.mk.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sh/transliteration.sh.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/nn/transliteration.nn.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/az/transliteration.az.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/bg/transliteration.bg.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ka/transliteration.ka.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/gl/transliteration.gl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/am/transliteration.am.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/yi/transliteration.yi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/no/transliteration.no.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/et/transliteration.et.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ja/transliteration.ja.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ht/transliteration.ht.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/be/transliteration.be.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/el/transliteration.el.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/cy/transliteration.cy.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sq/transliteration.sq.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/mr/transliteration.mr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/hy/transliteration.hy.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sl/transliteration.sl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ko/transliteration.ko.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ga/transliteration.ga.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/bn/transliteration.bn.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sr/transliteration.sr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/fi/transliteration.fi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ca/transliteration.ca.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/hr/transliteration.hr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/nl/transliteration.nl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sv/transliteration.sv.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/tl/transliteration.tl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/da/transliteration.da.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/kn/transliteration.kn.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/mt/transliteration.mt.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sw/transliteration.sw.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/lv/transliteration.lv.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/te/transliteration.te.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/uk/transliteration.uk.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ro/transliteration.ro.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/fa/transliteration.fa.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/la/transliteration.la.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/sk/transliteration.sk.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/is/transliteration.is.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/pt/transliteration.pt.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ur/transliteration.ur.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/gu/transliteration.gu.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ta/transliteration.ta.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/km/transliteration.km.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ms/transliteration.ms.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/af/transliteration.af.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/eu/transliteration.eu.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/pl/transliteration.pl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/de/transliteration.de.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/eo/transliteration.eo.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/id/transliteration.id.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/zh/transliteration.zh.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/cs/transliteration.cs.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/he/transliteration.he.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/lt/transliteration.lt.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/tr/transliteration.tr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/bs/transliteration.bs.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/hu/transliteration.hu.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/th/transliteration.th.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/transliteration2/ru/transliteration.ru.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/pam/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/it/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/hsb/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sah/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/hi/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/fr/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/es/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/vi/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ar/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/mk/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ps/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sh/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/arz/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/nn/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/su/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/scn/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/az/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/bg/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/yo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/tg/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ka/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/tt/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/gl/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/mg/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ug/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/am/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/vec/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/yi/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/no/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/als/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/et/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/vls/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/dv/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ja/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ilo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ht/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/zhc/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/be/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/el/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/os/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/cy/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ml/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sq/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/mr/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/hy/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sl/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ko/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/br/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ga/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/lb/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/bn/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sr/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/hif/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/jv/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/fi/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/gan/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ky/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ca/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/qu/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/hr/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/nl/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sv/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/io/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/tl/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sa/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/pms/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ast/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/da/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ceb/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/fy/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/kn/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sco/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/mt/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sw/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/li/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/war/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/lmo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/uz/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ku/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/lv/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/my/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/an/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/vo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/se/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/fo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/kk/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/te/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/uk/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/as/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/cv/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/szl/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/tk/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ro/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/fa/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/bo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/la/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/sk/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/si/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/bar/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/is/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/mn/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/wa/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/pt/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ur/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/gu/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/gv/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ta/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/km/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/en/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ms/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ce/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/bpy/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/af/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/eu/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/pl/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/de/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/eo/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/id/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/oc/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/zh/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/cs/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/he/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/rm/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/lt/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/tr/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ne/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/bs/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ia/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/diq/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/or/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/hu/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/gd/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ba/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/th/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/pa/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/embeddings2/ru/embeddings_pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/it/it.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/hi/hi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/fr/fr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/es/es.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/vi/vi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ar/ar.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/mk/mk.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sh/sh.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/nn/nn.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/az/az.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/bg/bg.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ka/ka.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/gl/gl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/yi/yi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/no/no.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/et/et.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ja/ja.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ht/ht.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/be/be.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/el/el.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/cy/cy.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sq/sq.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/mr/mr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/hy/hy.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sl/sl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ko/ko.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ga/ga.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/bn/bn.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sr/sr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/fi/fi.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ca/ca.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/hr/hr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/nl/nl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sv/sv.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/tl/tl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/da/da.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/kn/kn.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/mt/mt.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sw/sw.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/lv/lv.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/te/te.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/uk/uk.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ro/ro.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/fa/fa.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/la/la.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/sk/sk.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/is/is.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/pt/pt.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ur/ur.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/gu/gu.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ta/ta.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/km/km.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/en/en.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ms/ms.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/af/af.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/eu/eu.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/pl/pl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/de/de.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/eo/eo.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/id/id.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/zh/zh.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/cs/cs.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/lt/lt.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/tr/tr.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/bs/bs.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/hu/hu.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/th/th.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/uniemb/ru/ru.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/it/it-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/fr/fr-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/es/es-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/bg/bg-CoNLL06.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/sl/sl-CoNLL06.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/ga/ga-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/fi/fi-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/nl/nl-CoNLL06.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/sv/sv-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/da/da-CoNLL06.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/pt/pt-CoNLL06.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/en/en-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/de/de-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/id/id-UD-wip.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/cs/cs-CoNLL06.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/pos2/hu/hu-UD.npz.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/pam/pam.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/it/it.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/hsb/hsb.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sah/sah.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/hi/hi.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/fr/fr.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/es/es.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/vi/vi.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ar/ar.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/mk/mk.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ps/ps.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sh/sh.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/arz/arz.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/nn/nn.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/su/su.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/scn/scn.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/az/az.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/bg/bg.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/yo/yo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/tg/tg.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ka/ka.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/tt/tt.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/gl/gl.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/mg/mg.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ug/ug.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/am/am.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/vec/vec.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/yi/yi.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/no/no.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/als/als.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/et/et.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/vls/vls.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/dv/dv.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ja/ja.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ilo/ilo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ht/ht.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/be/be.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/el/el.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/os/os.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/cy/cy.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ml/ml.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sq/sq.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/mr/mr.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/hy/hy.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sl/sl.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ko/ko.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/br/br.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ga/ga.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/lb/lb.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/bn/bn.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sr/sr.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/hif/hif.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/jv/jv.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/fi/fi.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/gan/gan.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ky/ky.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ca/ca.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/qu/qu.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/hr/hr.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/nl/nl.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sv/sv.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/io/io.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/tl/tl.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sa/sa.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/pms/pms.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ast/ast.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/da/da.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ceb/ceb.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/fy/fy.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/kn/kn.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sco/sco.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/mt/mt.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sw/sw.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/li/li.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/war/war.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/lmo/lmo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/uz/uz.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ku/ku.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/lv/lv.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/my/my.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/an/an.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/vo/vo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/se/se.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/fo/fo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/kk/kk.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/te/te.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/uk/uk.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/as/as.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/cv/cv.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/szl/szl.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/tk/tk.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ro/ro.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/fa/fa.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/bo/bo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/la/la.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/sk/sk.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/si/si.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/bar/bar.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/is/is.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/mn/mn.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/wa/wa.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/pt/pt.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ur/ur.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/gu/gu.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/gv/gv.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ta/ta.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/zhw/zhw.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/km/km.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/en/en.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ms/ms.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ce/ce.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/bpy/bpy.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/af/af.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/eu/eu.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/pl/pl.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/de/de.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/eo/eo.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/id/id.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/oc/oc.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/zh/zh.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/cs/cs.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/he/he.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/rm/rm.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/lt/lt.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/tr/tr.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ne/ne.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/bs/bs.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ia/ia.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/diq/diq.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/or/or.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/hu/hu.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/gd/gd.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ba/ba.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/th/th.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/pa/pa.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/sentiment2/ru/ru.sent.pkl.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/pam/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/it/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/hsb/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sah/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/hi/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/fr/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/es/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/vi/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ar/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/mk/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ps/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sh/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/arz/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/nn/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/su/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/scn/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/az/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/bg/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/yo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/tg/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ka/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/tt/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/gl/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/mg/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ug/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/am/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/vec/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/yi/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/no/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/als/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/et/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/vls/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/dv/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ja/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ilo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ht/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/zhc/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/be/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/el/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/os/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/cy/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ml/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sq/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/mr/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/hy/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sl/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ko/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/br/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ga/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/lb/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/bn/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sr/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/hif/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/jv/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/fi/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/gan/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ky/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ca/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/qu/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/hr/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/nl/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sv/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/io/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/tl/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sa/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/pms/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ast/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/da/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ceb/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/fy/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/kn/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sco/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/mt/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sw/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/li/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/war/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/lmo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/uz/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ku/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/lv/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/my/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/an/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/vo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/se/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/fo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/kk/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/te/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/uk/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/as/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/cv/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/szl/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/tk/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ro/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/fa/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/bo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/la/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/sk/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/si/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/bar/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/is/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/mn/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/wa/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/pt/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ur/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/gu/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/gv/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ta/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/km/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/en/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ms/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ce/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/bpy/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/af/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/eu/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/pl/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/de/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/eo/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/id/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/oc/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/zh/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/cs/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/he/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/rm/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/lt/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/tr/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ne/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/bs/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ia/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/diq/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/or/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/hu/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/gd/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ba/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/th/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/pa/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/tsne2/ru/embeddings_tsne.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/pam/pam.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/it/it.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/hsb/hsb.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sah/sah.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/hi/hi.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/fr/fr.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/es/es.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/vi/vi.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ar/ar.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/mk/mk.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ps/ps.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sh/sh.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/arz/arz.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/nn/nn.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/su/su.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/scn/scn.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/az/az.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/bg/bg.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/yo/yo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/tg/tg.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ka/ka.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/tt/tt.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/gl/gl.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/mg/mg.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ug/ug.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/am/am.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/vec/vec.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/yi/yi.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/no/no.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/als/als.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/et/et.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/vls/vls.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/dv/dv.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ja/ja.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ilo/ilo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ht/ht.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/be/be.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/el/el.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/os/os.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/cy/cy.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ml/ml.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sq/sq.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/mr/mr.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/hy/hy.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sl/sl.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ko/ko.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/br/br.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ga/ga.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/lb/lb.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/bn/bn.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sr/sr.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/hif/hif.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/jv/jv.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/fi/fi.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/gan/gan.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ky/ky.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ca/ca.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/qu/qu.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/hr/hr.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/nl/nl.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sv/sv.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/io/io.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/tl/tl.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sa/sa.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/pms/pms.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ast/ast.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/da/da.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ceb/ceb.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/fy/fy.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/kn/kn.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sco/sco.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/mt/mt.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sw/sw.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/li/li.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/war/war.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/lmo/lmo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/uz/uz.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ku/ku.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/lv/lv.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/my/my.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/an/an.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/vo/vo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/se/se.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/fo/fo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/kk/kk.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/te/te.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/uk/uk.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/as/as.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/cv/cv.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/szl/szl.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/tk/tk.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ro/ro.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/fa/fa.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/bo/bo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/la/la.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/sk/sk.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/si/si.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/bar/bar.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/is/is.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/mn/mn.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/wa/wa.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/pt/pt.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ur/ur.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/gu/gu.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/gv/gv.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ta/ta.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/km/km.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/en/en.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ms/ms.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ce/ce.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/bpy/bpy.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/af/af.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/eu/eu.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/pl/pl.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/de/de.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/eo/eo.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/id/id.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/oc/oc.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/zh/zh.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/cs/cs.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/he/he.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/rm/rm.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/lt/lt.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/tr/tr.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ne/ne.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/bs/bs.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ia/ia.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/diq/diq.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/or/or.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/hu/hu.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/gd/gd.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ba/ba.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/th/th.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/pa/pa.morph.tar.bz2
	http://polyglot.cs.stonybrook.edu/~polyglot/morph2/ru/ru.morph.tar.bz2"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="doc test"

RDEPEND="dev-libs/icu
	dev-python/wheel[${PYTHON_USEDEP}]
	dev-python/pyicu[${PYTHON_USEDEP}]
	dev-python/pycld2[${PYTHON_USEDEP}]
	dev-python/six[${PYTHON_USEDEP}]
	dev-python/futures[${PYTHON_USEDEP}]
	dev-python/Morfessor[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]"

DEPEND="${RDEPEND}"
